### ISSUE TITLE
analog status sourceName not implemented

### ISSUE THREAD

**Issue by kivel** [paulscherrerinstitute/ecmccfg#164]
The header states the source name for the status can be provided. But, it's actually not implemented.

https://github.com/paulscherrerinstitute/ecmccfg/blob/ecdcb0c766c7dce9d839b2df19fd70df3d783882/db/generic/ecmc_status_analog-chX.template#L8

@anderssandstrom should I implement a macro to make the `sourceName` selectable, or stay like this to enforce `status` for the mapping?

**Comment by anderssandstrom** [comment]
@kivel I think the status macro is not currently used so I think we can just update/remove the text in the header?!

**Comment by kivel** [comment]
@anderssandstrom OK, I'll do it

**Comment by kivel** [comment]
fixed here eb71021774637461e1fdb0ce6d05b4b7d9521512
