### ISSUE TITLE
how to map a two bit PDO?

### ISSUE THREAD

**Issue by kivel** [paulscherrerinstitute/ecmccfg#165]
@anderssandstrom Any idea how this can be mapped and bound to a PV in EPICS?
https://github.com/paulscherrerinstitute/ecmccfg/blob/ecdcb0c766c7dce9d839b2df19fd70df3d783882/hardware/Beckhoff_3XXX/ecmcAnalogInput_16bit.cmd#L7-L8

**Comment by anderssandstrom** [comment]
Hi @kivel,
If this question is for this specific case then it's already mapped in the 16bit status word.
If your question is more generic you should be able to use the datatype "B2" in Cfg.EcAddEntryDT(). Not sure it's used anywhere, maybe for a KL terminal.
