### ISSUE TITLE
AM8112-0FH0 current

### ISSUE THREAD

**Issue by kivel** [paulscherrerinstitute/ecmccfg#205]
Can somebody please verify those numbers by reading the electronic nameplate of the motor.
The current looks way too high for such a small motor.

https://github.com/paulscherrerinstitute/ecmccfg/blob/aee73778d4db11db49704774f518ebc645460cee/hardware/Motors/ecmcEL72XX-XXXX-Motor-Beckhoff-AM8112-0FH0-0000.cmd#L16C1-L19C84

**Comment by anderssandstrom** [comment]
I checked in twincat and it seems to be corrrect.

**Comment by kivel** [comment]
curious
